#!/usr/bin python3
# -*- coding: utf-8 -*-

"""
Created on Dec 12 2017

@author: sonounoteam (view licence)
"""

import wx
import gui.frame_implementation as gui


class SonoUnoCore (gui.SonoUnoGUI):


    def __init__(self):
        
        """
        This class overwrite the specific modules to able the use of different
        sonoUno modes.
        This class use the specific scripts designed to open different data 
        sets.
        This method initialize all the class variables.
        """
        # This class inherit from gui module, class FrameDesign
        gui.SonoUnoGUI.__init__(self)
        
    # def open_method(self, datatype=1):
        
    #     """
    #     This method allow to open a dataset serching it on the computer file
    #     system.
    #     """
    #     datatype = int(datatype)
        
    

if __name__ == '__main__':
    # Script2.py executed as script
    # do something
    # But I realize that I need to run the gui from here if I want to overwrite
    # some GUI methods
    #exec(open("gui/frame_implementation.py").read())
    
    app = wx.App()
    frame = SonoUnoCore()
    frame.Show()
    app.MainLoop()